antibody_pdb = '4G6K'
antigen_pdb = '4I1B'
complex_pdb = '4G6M'
out_path = './data/antibody'
ab_pdb = f'{out_path}/pre/{antibody_pdb}_0.pdb'
ag_pdb = f'{out_path}/pre/{antigen_pdb}_0.pdb'
cx_pdb = f'{out_path}/pre/{complex_pdb}_0.pdb'

antibody_prep = f'{out_path}/pre/{antibody_pdb}_clean.pdb'
antigen_prep = f'{out_path}/pre/{antigen_pdb}_clean.pdb'
complex_prep = f'{out_path}/pre/{complex_pdb}_clean.pdb'

ab_actpass = f'{out_path}/pre/{antibody_pdb}_actpass.txt'
ag_actpass = f'{out_path}/pre/{antigen_pdb}_actpass.txt'
complex_tbl = f'{out_path}/pre/ambig-paratope-NMR-epitope.tbl'
body_tbl = f'{out_path}/pre/antibody-unambig.tbl'

haddock_wf_data = f'{out_path}/docking/haddock_wf_data'
mol1_output_top_zip_path = f'{out_path}/docking/step_outputs/1_top_mol1.zip'
mol2_output_top_zip_path = f'{out_path}/docking/step_outputs/1_top_mol2.zip'
docking_output_zip_path = f'{out_path}/docking/step_outputs/2_docking.zip'
output_evaluation_zip_path = f'{out_path}/docking/step_outputs/3_caprieval.zip'
output_selection_zip_path = f'{out_path}/docking/step_outputs/4_selected.zip'
refinement_output_zip_path = f'{out_path}/docking/step_outputs/5_flexref.zip'
output_evaluation_zip_path2 = f'{out_path}/docking/step_outputs/6_caprieval2.zip'
refinement_output_zip_path = f'{out_path}/docking/step_outputs/7_emref.zip'
output_evaluation_zip_path3 = f'{out_path}/docking/step_outputs/8_caprieval3.zip'
output_cluster_zip_path = f'{out_path}/docking/step_outputs/9_clustfcc.zip'
output_seletopclusts_zip_path = f'{out_path}/docking/step_outputs/10_seletopclusts.zip'
output_evaluation_zip_path4 = f'{out_path}/docking/step_outputs/11_caprieval4.zip'
output_contactmap_zip_path = f'{out_path}/docking/step_outputs/12_contact_map.zip'
