kind: horus_workflow
name: BioExcel Virtual Screening - Protein-Ligand Docking - Cluster90 Binding Site

_executor: &executor
  kind: conda_python_environment
  environment_dir: "../.horus_conda_env"
  conda: conda
  environment_file: conda_env.yaml

_docker_executor: &docker_executor
  kind: docker
  image: quay.io/biocontainers/biobb_vs:5.2.1--pyhdfd78af_0

tasks:
  - kind: horus_task
    id: create_results_folder
    name: Create results folder
    outputs:
      - id: results_dir
        kind: folder
        path: results
    executor: *executor
    runtime:
      kind: command
      command: mkdir -p ${results_dir}
    target:
      kind: local
  - kind: horus_task
    id: fetch_pdb
    name: Download 3HEC structure from PDB
    inputs:
      - id: results_dir
        kind: folder
        path: results
      - id: fetch_pdb_config
        kind: file
        path: configs/fetch_pdb.yaml
    outputs:
      - id: download_pdb
        kind: file
        path: results/download.pdb
    executor: *executor
    runtime:
      kind: command
      command: >-
        pdb
        --config ${fetch_pdb_config}
        --output_pdb_path ${download_pdb}
    target:
      kind: local

  - kind: horus_task
    id: extract_molecule
    name: Extract protein structure from downloaded PDB
    inputs:
      - id: download_pdb
        kind: file
        path: results/download.pdb
    outputs:
      - id: pdb_protein
        kind: file
        path: results/pdb_protein.pdb
    executor: *executor
    runtime:
      kind: command
      command: >-
        extract_molecule
        --input_structure_path ${download_pdb}
        --output_molecule_path ${pdb_protein}
    target:
      kind: local

  - kind: horus_task
    id: pdb_cluster_zip
    name: Download PDB Cluster90 collection for 3HEC
    inputs:
      - id: results_dir
        kind: folder
        path: results
      - id: pdb_cluster_zip_config
        kind: file
        path: configs/pdb_cluster_zip.yaml
    outputs:
      - id: pdb_cluster
        kind: file
        path: results/pdb_cluster.zip
    executor: *executor
    runtime:
      kind: command
      command: >-
        pdb_cluster_zip
        --config ${pdb_cluster_zip_config}
        --output_pdb_zip_path ${pdb_cluster}
    target:
      kind: local

  - kind: horus_task
    id: bindingsite
    name: Extract binding site from Cluster90 collection
    inputs:
      - id: bindingsite_config
        kind: file
        path: configs/bindingsite.yaml
      - id: pdb_protein
        kind: file
        path: results/pdb_protein.pdb
      - id: pdb_cluster
        kind: file
        path: results/pdb_cluster.zip
    outputs:
      - id: output_bindingsite
        kind: file
        path: results/bindingsite.pdb
    executor: *docker_executor
    runtime:
      kind: command
      command: >-
        bindingsite
        --config ${bindingsite_config}
        --input_pdb_path ${pdb_protein}
        --input_clusters_zip ${pdb_cluster}
        --output_pdb_path ${output_bindingsite}
    target:
      kind: local

  - kind: horus_task
    id: box
    name: Generate cavity box around binding site
    inputs:
      - id: box_config
        kind: file
        path: configs/box.yaml
      - id: output_bindingsite
        kind: file
        path: results/bindingsite.pdb
    outputs:
      - id: output_box
        kind: file
        path: results/box.pdb
    executor: *docker_executor
    runtime:
      kind: command
      command: >-
        box
        --config ${box_config}
        --input_pdb_path ${output_bindingsite}
        --output_pdb_path ${output_box}
    target:
      kind: local

  - kind: horus_task
    id: ideal_sdf
    name: Download Imatinib (STI) small molecule as SDF
    inputs:
      - id: results_dir
        kind: folder
        path: results
      - id: ideal_sdf_config
        kind: file
        path: configs/ideal_sdf.yaml
    outputs:
      - id: sdf_ideal
        kind: file
        path: results/ideal.sdf
    executor: *executor
    runtime:
      kind: command
      command: >-
        ideal_sdf
        --config ${ideal_sdf_config}
        --output_sdf_path ${sdf_ideal}
    target:
      kind: local

  - kind: horus_task
    id: babel_convert_sdf2pdb
    name: Convert small molecule from SDF to PDB format
    inputs:
      - id: babel_convert_sdf2pdb_config
        kind: file
        path: configs/babel_convert_sdf2pdb.yaml
      - id: sdf_ideal
        kind: file
        path: results/ideal.sdf
    outputs:
      - id: ligand_pdb
        kind: file
        path: results/ligand.pdb
    executor: *executor
    runtime:
      kind: command
      command: >-
        babel_convert
        --config ${babel_convert_sdf2pdb_config}
        --input_path ${sdf_ideal}
        --output_path ${ligand_pdb}
    target:
      kind: local

  - kind: horus_task
    id: babel_convert_pdb2pdbqt
    name: Prepare ligand for docking (PDB to PDBQT)
    inputs:
      - id: babel_convert_pdb2pdbqt_config
        kind: file
        path: configs/babel_convert_pdb2pdbqt.yaml
      - id: ligand_pdb
        kind: file
        path: results/ligand.pdb
    outputs:
      - id: prep_ligand
        kind: file
        path: results/prep_ligand.pdbqt
    executor: *executor
    runtime:
      kind: command
      command: >-
        babel_convert
        --config ${babel_convert_pdb2pdbqt_config}
        --input_path ${ligand_pdb}
        --output_path ${prep_ligand}
    target:
      kind: local

  - kind: horus_task
    id: str_check_add_hydrogens
    name: Prepare receptor protein for docking (PDB to PDBQT)
    inputs:
      - id: str_check_add_hydrogens_config
        kind: file
        path: configs/str_check_add_hydrogens.yaml
      - id: pdb_protein
        kind: file
        path: results/pdb_protein.pdb
    outputs:
      - id: prep_receptor
        kind: file
        path: results/prep_receptor.pdbqt
    executor: *executor
    runtime:
      kind: command
      command: >-
        str_check_add_hydrogens
        --config ${str_check_add_hydrogens_config}
        --input_structure_path ${pdb_protein}
        --output_structure_path ${prep_receptor}
    target:
      kind: local

  - kind: horus_task
    id: autodock_vina_run
    name: Run AutoDock Vina docking
    inputs:
      - id: prep_ligand
        kind: file
        path: results/prep_ligand.pdbqt
      - id: prep_receptor
        kind: file
        path: results/prep_receptor.pdbqt
      - id: output_box
        kind: file
        path: results/box.pdb
    outputs:
      - id: output_vina_pdbqt
        kind: file
        path: results/output_vina.pdbqt
      - id: output_vina_log
        kind: file
        path: results/output_vina.log
    executor: *docker_executor
    runtime:
      kind: command
      command: >-
        autodock_vina_run
        --input_ligand_pdbqt_path ${prep_ligand}
        --input_receptor_pdbqt_path ${prep_receptor}
        --input_box_path ${output_box}
        --output_pdbqt_path ${output_vina_pdbqt}
        --output_log_path ${output_vina_log}
    target:
      kind: local

  - kind: horus_task
    id: extract_model_pdbqt
    name: Extract top docking pose from Vina output
    inputs:
      - id: extract_model_pdbqt_config
        kind: file
        path: configs/extract_model_pdbqt.yaml
      - id: output_vina_pdbqt
        kind: file
        path: results/output_vina.pdbqt
    outputs:
      - id: output_pdbqt_model
        kind: file
        path: results/output_model.pdbqt
    executor: *docker_executor
    runtime:
      kind: command
      command: >-
        extract_model_pdbqt
        --config ${extract_model_pdbqt_config}
        --input_pdbqt_path ${output_vina_pdbqt}
        --output_pdbqt_path ${output_pdbqt_model}
    target:
      kind: local

  - kind: horus_task
    id: babel_convert_pdbqt2pdb
    name: Convert docking pose from PDBQT to PDB format
    inputs:
      - id: babel_convert_pdbqt2pdb_config
        kind: file
        path: configs/babel_convert_pdbqt2pdb.yaml
      - id: output_pdbqt_model
        kind: file
        path: results/output_model.pdbqt
    outputs:
      - id: output_pdb_model
        kind: file
        path: results/output_model.pdb
    executor: *executor
    runtime:
      kind: command
      command: >-
        babel_convert
        --config ${babel_convert_pdbqt2pdb_config}
        --input_path ${output_pdbqt_model}
        --output_path ${output_pdb_model}
    target:
      kind: local

  - kind: horus_task
    id: cat_pdb
    name: Combine protein and docked ligand into final structure
    inputs:
      - id: pdb_protein
        kind: file
        path: results/pdb_protein.pdb
      - id: output_pdb_model
        kind: file
        path: results/output_model.pdb
    outputs:
      - id: output_structure
        kind: file
        path: results/output_structure.pdb
    executor: *executor
    runtime:
      kind: command
      command: >-
        cat_pdb
        --input_structure1 ${pdb_protein}
        --input_structure2 ${output_pdb_model}
        --output_structure_path ${output_structure}
    target:
      kind: local

edges:
  - source: fetch_pdb
    source_output: download_pdb
    target: extract_molecule
    target_input: download_pdb

  - source: extract_molecule
    source_output: pdb_protein
    target: bindingsite
    target_input: pdb_protein

  - source: extract_molecule
    source_output: pdb_protein
    target: str_check_add_hydrogens
    target_input: pdb_protein

  - source: extract_molecule
    source_output: pdb_protein
    target: cat_pdb
    target_input: pdb_protein

  - source: pdb_cluster_zip
    source_output: pdb_cluster
    target: bindingsite
    target_input: pdb_cluster

  - source: bindingsite
    source_output: output_bindingsite
    target: box
    target_input: output_bindingsite

  - source: box
    source_output: output_box
    target: autodock_vina_run
    target_input: output_box

  - source: ideal_sdf
    source_output: sdf_ideal
    target: babel_convert_sdf2pdb
    target_input: sdf_ideal

  - source: babel_convert_sdf2pdb
    source_output: ligand_pdb
    target: babel_convert_pdb2pdbqt
    target_input: ligand_pdb

  - source: babel_convert_pdb2pdbqt
    source_output: prep_ligand
    target: autodock_vina_run
    target_input: prep_ligand

  - source: str_check_add_hydrogens
    source_output: prep_receptor
    target: autodock_vina_run
    target_input: prep_receptor

  - source: autodock_vina_run
    source_output: output_vina_pdbqt
    target: extract_model_pdbqt
    target_input: output_vina_pdbqt

  - source: extract_model_pdbqt
    source_output: output_pdbqt_model
    target: babel_convert_pdbqt2pdb
    target_input: output_pdbqt_model

  - source: babel_convert_pdbqt2pdb
    source_output: output_pdb_model
    target: cat_pdb
    target_input: output_pdb_model

  - source: create_results_folder
    source_output: results_dir
    target: fetch_pdb
    target_input: results_dir

  - source: create_results_folder
    source_output: results_dir
    target: pdb_cluster_zip
    target_input: results_dir

  - source: create_results_folder
    source_output: results_dir
    target: ideal_sdf
    target_input: results_dir

orchestrator_target:
  kind: local
  working_directory: "./workflow_results"
